/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.wws.plugin

import com.android.build.gradle.AppExtension
import com.wws.helloplugin.LoggerTransform
import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
public class HelloPlugin implements Plugin<Project> {
    public void apply(Project project) {
        def android = project.extensions.getByType(AppExtension)
        android.registerTransform(new LoggerTransform());
    }
}
